"""
train_model.py
==============
Synthetic training-data generator + model trainer for the Keylogger
Detection System.

What it does
------------
1. Generates a labelled CSV dataset of realistic feature vectors for three
   classes: safe, suspicious, malicious.
2. Trains a scikit-learn Pipeline (StandardScaler + Gradient Boosting or
   Random Forest — configurable via --model-type).
3. Evaluates the model with stratified k-fold cross-validation and prints a
   classification report on a held-out test set.
4. Serialises the trained pipeline + metadata to models/keylogger_detector.joblib.
   The running detector hot-reloads this file automatically.

Synthetic data design
---------------------
Each class is generated by sampling from per-class distributions that encode
real-world knowledge about how keyloggers differ from benign processes:

  safe      : No hook APIs, visible window, low I/O, signed, system/standard apps.
  suspicious: Hook APIs present but ambiguous (accessibility tools, macro apps).
              Sometimes no window, some file writes, maybe one startup entry.
  malicious : Strong hook signals, hidden, high network send after keystrokes,
              running from temp dirs, startup persistence, unsigned.

Usage
-----
  python tools/train_model.py                      # train with defaults
  python tools/train_model.py --samples 5000       # larger dataset
  python tools/train_model.py --model-type rf      # Random Forest
  python tools/train_model.py --output models/my_model.joblib
  python tools/train_model.py --csv data/training_data.csv  # save dataset
  python tools/train_model.py --load-csv data/real_data.csv # train on real data

Real data
---------
  If you have collected labelled real process snapshots (e.g. from sandbox
  runs), export them as a CSV with columns matching FEATURE_NAMES plus a
  "label" column ("safe"/"suspicious"/"malicious"), then pass --load-csv.
  The script will train on that data instead of the synthetic set.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).parent.parent.resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.feature_extractor import FEATURE_NAMES, NUM_FEATURES  # noqa: E402

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Label constants
# ---------------------------------------------------------------------------
LABELS      = ["safe", "suspicious", "malicious"]
LABEL_INT   = {l: i for i, l in enumerate(LABELS)}
INT_LABEL   = {i: l for i, l in enumerate(LABELS)}

# ---------------------------------------------------------------------------
# Per-class feature distributions
# ---------------------------------------------------------------------------
# Each entry is (mean, std, clip_min, clip_max)
# Order matches FEATURE_NAMES exactly.

_DIST: Dict[str, List[Tuple[float, float, float, float]]] = {
    #                         mean   std   min   max
    "safe": [
        (0.30,  0.45, 0.0, 1.0),   # hook_api_present         (some benign use user32)
        (0.00,  0.05, 0.0, 1.0),   # has_ll_keyboard_hook
        (0.40,  0.60, 0.0, 4.0),   # hook_related_dll_count
        (0.90,  0.20, 0.0, 1.0),   # has_visible_window
        (1.80,  1.20, 0.0, 8.0),   # window_count
        (3.50,  4.00, 0.0, 40.0),  # cpu_mean
        (8.00,  8.00, 0.0, 60.0),  # cpu_max
        (80.0,  60.0, 2.0, 500.0), # mem_rss_mb_mean
        (5e5,   8e5,  0.0, 5e6),   # file_write_bytes_sum
        (100.0, 200.0, 0.0, 2000), # file_write_rate
        (5.0,   4.0,  0.0, 30.0),  # open_file_count_mean
        (1.2,   1.5,  0.0, 10.0),  # net_connections_mean
        (2e4,   3e4,  0.0, 2e5),   # net_bytes_sent_sum
        (0.70,  0.40, 0.0, 1.0),   # is_signed
        (0.20,  0.35, 0.0, 1.0),   # is_system_process
        (0.05,  0.18, 0.0, 1.0),   # has_startup_entry
        (0.02,  0.12, 0.0, 1.0),   # no_exe_path
        (0.05,  0.18, 0.0, 1.0),   # cmdline_empty
        (9.0,   4.0,  2.0, 25.0),  # name_length
        (0.01,  0.08, 0.0, 1.0),   # running_from_temp
        (0.15,  0.30, 0.0, 1.0),   # running_from_appdata
        (3600,  7200, 30, 86400),   # age_seconds
        (0.02,  0.12, 0.0, 1.0),   # hook_no_window
        (0.01,  0.08, 0.0, 1.0),   # hook_with_network
    ],
    "suspicious": [
        (0.75,  0.35, 0.0, 1.0),   # hook_api_present
        (0.10,  0.25, 0.0, 1.0),   # has_ll_keyboard_hook
        (1.50,  1.00, 0.0, 5.0),   # hook_related_dll_count
        (0.55,  0.40, 0.0, 1.0),   # has_visible_window
        (0.70,  0.80, 0.0, 4.0),   # window_count
        (2.50,  3.00, 0.0, 25.0),  # cpu_mean
        (6.00,  7.00, 0.0, 40.0),  # cpu_max
        (45.0,  35.0, 2.0, 300.0), # mem_rss_mb_mean
        (8e5,   1e6,  0.0, 8e6),   # file_write_bytes_sum
        (300.0, 500.0, 0.0, 4000), # file_write_rate
        (6.0,   5.0,  0.0, 35.0),  # open_file_count_mean
        (2.5,   2.5,  0.0, 12.0),  # net_connections_mean
        (1e5,   2e5,  0.0, 1e6),   # net_bytes_sent_sum
        (0.35,  0.40, 0.0, 1.0),   # is_signed
        (0.05,  0.18, 0.0, 1.0),   # is_system_process
        (0.30,  0.40, 0.0, 1.0),   # has_startup_entry
        (0.10,  0.25, 0.0, 1.0),   # no_exe_path
        (0.20,  0.35, 0.0, 1.0),   # cmdline_empty
        (7.0,   3.5,  2.0, 20.0),  # name_length
        (0.15,  0.30, 0.0, 1.0),   # running_from_temp
        (0.25,  0.35, 0.0, 1.0),   # running_from_appdata
        (900,   1800, 30, 43200),   # age_seconds
        (0.40,  0.40, 0.0, 1.0),   # hook_no_window
        (0.25,  0.35, 0.0, 1.0),   # hook_with_network
    ],
    "malicious": [
        (0.95,  0.15, 0.0, 1.0),   # hook_api_present
        (0.75,  0.35, 0.0, 1.0),   # has_ll_keyboard_hook
        (2.80,  1.20, 0.0, 6.0),   # hook_related_dll_count
        (0.08,  0.20, 0.0, 1.0),   # has_visible_window
        (0.05,  0.15, 0.0, 2.0),   # window_count
        (1.50,  2.00, 0.0, 15.0),  # cpu_mean
        (3.50,  4.00, 0.0, 20.0),  # cpu_max
        (22.0,  18.0, 1.0, 120.0), # mem_rss_mb_mean
        (2e6,   2e6,  0.0, 1.2e7), # file_write_bytes_sum  (writing keystroke logs)
        (800.0, 900.0, 0.0, 8000), # file_write_rate
        (3.0,   3.0,  0.0, 18.0),  # open_file_count_mean
        (4.5,   3.0,  0.0, 15.0),  # net_connections_mean  (exfiltration)
        (2e6,   3e6,  0.0, 2e7),   # net_bytes_sent_sum
        (0.05,  0.18, 0.0, 1.0),   # is_signed
        (0.00,  0.05, 0.0, 1.0),   # is_system_process
        (0.70,  0.35, 0.0, 1.0),   # has_startup_entry
        (0.40,  0.40, 0.0, 1.0),   # no_exe_path
        (0.60,  0.40, 0.0, 1.0),   # cmdline_empty
        (6.0,   3.0,  2.0, 18.0),  # name_length
        (0.65,  0.40, 0.0, 1.0),   # running_from_temp
        (0.15,  0.30, 0.0, 1.0),   # running_from_appdata
        (300,   600,  10, 10800),   # age_seconds           (fresh processes)
        (0.88,  0.25, 0.0, 1.0),   # hook_no_window
        (0.80,  0.30, 0.0, 1.0),   # hook_with_network
    ],
}

# Validate distribution table at import time
assert all(len(v) == NUM_FEATURES for v in _DIST.values()), (
    "Distribution table row count doesn't match NUM_FEATURES"
)


# ---------------------------------------------------------------------------
# Synthetic data generator
# ---------------------------------------------------------------------------

def generate_dataset(
    n_safe: int = 1500,
    n_suspicious: int = 750,
    n_malicious: int = 750,
    seed: int = 42,
) -> pd.DataFrame:
    """
    Generate a labelled synthetic dataset.

    Returns a DataFrame with columns = FEATURE_NAMES + ["label"].
    """
    rng = np.random.default_rng(seed)
    rows: List[np.ndarray] = []
    labels: List[str] = []

    class_counts = {
        "safe":       n_safe,
        "suspicious": n_suspicious,
        "malicious":  n_malicious,
    }

    for cls, count in class_counts.items():
        dist = _DIST[cls]
        for _ in range(count):
            features = np.array([
                float(np.clip(rng.normal(mean, std), lo, hi))
                for mean, std, lo, hi in dist
            ], dtype=np.float32)

            # Binary features: round to 0/1
            binary_indices = [
                0, 1, 3, 13, 14, 15, 16, 17, 19, 20, 22, 23
            ]
            for idx in binary_indices:
                features[idx] = float(round(min(max(features[idx], 0.0), 1.0)))

            rows.append(features)
            labels.append(cls)

    X = np.stack(rows)
    df = pd.DataFrame(X, columns=FEATURE_NAMES)
    df["label"] = labels

    # Shuffle
    df = df.sample(frac=1, random_state=seed).reset_index(drop=True)

    logger.info(
        "Generated dataset: %d safe, %d suspicious, %d malicious  (%d total)",
        n_safe, n_suspicious, n_malicious, len(df),
    )
    return df


# ---------------------------------------------------------------------------
# Model training
# ---------------------------------------------------------------------------

def train(
    df: pd.DataFrame,
    model_type: str = "gb",
    n_estimators: int = 300,
    test_size: float = 0.20,
    cv_folds: int = 5,
    seed: int = 42,
) -> Tuple:
    """
    Train and evaluate a scikit-learn Pipeline on *df*.

    Parameters
    ----------
    df          : DataFrame with FEATURE_NAMES columns + "label" column.
    model_type  : "gb" = GradientBoostingClassifier, "rf" = RandomForestClassifier
    n_estimators: tree count for the ensemble
    test_size   : fraction of data held out for final evaluation
    cv_folds    : number of stratified cross-validation folds
    seed        : random seed

    Returns
    -------
    pipeline  : fitted sklearn Pipeline
    report    : classification report string
    cv_scores : array of CV accuracy scores
    """
    from sklearn.ensemble import (
        GradientBoostingClassifier,
        RandomForestClassifier,
    )
    from sklearn.metrics import classification_report
    from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler

    X = df[FEATURE_NAMES].values.astype(np.float32)
    y = df["label"].values

    # Encode labels to integers for cross_val_score, then decode back
    y_int = np.array([LABEL_INT[l] for l in y])

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, stratify=y, random_state=seed
    )

    if model_type == "rf":
        estimator = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=None,
            min_samples_leaf=2,
            n_jobs=-1,
            random_state=seed,
            class_weight="balanced",
        )
        model_name = "RandomForest"
    else:
        estimator = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=0.08,
            max_depth=5,
            subsample=0.8,
            random_state=seed,
        )
        model_name = "GradientBoosting"

    pipeline = Pipeline([
        ("scaler",     StandardScaler()),
        ("classifier", estimator),
    ])

    # Cross-validation
    logger.info("Running %d-fold cross-validation with %s…", cv_folds, model_name)
    cv_start = time.time()
    skf = StratifiedKFold(n_splits=cv_folds, shuffle=True, random_state=seed)
    cv_scores = cross_val_score(
        pipeline, X_train, y_train,
        cv=skf, scoring="f1_macro", n_jobs=-1,
    )
    logger.info(
        "CV F1-macro: %.3f ± %.3f  (%.1fs)",
        cv_scores.mean(), cv_scores.std(),
        time.time() - cv_start,
    )

    # Final fit on full training set
    logger.info("Fitting final model on %d training samples…", len(X_train))
    fit_start = time.time()
    pipeline.fit(X_train, y_train)
    logger.info("Training complete in %.1fs.", time.time() - fit_start)

    # Evaluate on held-out test set
    y_pred = pipeline.predict(X_test)
    report = classification_report(
        y_test, y_pred,
        target_names=LABELS,
        digits=3,
    )

    return pipeline, report, cv_scores


# ---------------------------------------------------------------------------
# Feature importance report
# ---------------------------------------------------------------------------

def _print_feature_importance(pipeline) -> None:
    try:
        clf = pipeline.named_steps["classifier"]
        if hasattr(clf, "feature_importances_"):
            importances = clf.feature_importances_
            pairs = sorted(
                zip(FEATURE_NAMES, importances),
                key=lambda x: x[1], reverse=True,
            )
            print("\nTop-10 Feature Importances:")
            print(f"  {'Feature':<30}  Importance")
            print("  " + "-" * 42)
            for name, imp in pairs[:10]:
                bar = "█" * int(imp * 60)
                print(f"  {name:<30}  {imp:.4f}  {bar}")
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Save model
# ---------------------------------------------------------------------------

def save_model(
    pipeline,
    output_path: Path,
    model_type: str,
    version: str,
) -> None:
    import joblib

    output_path.parent.mkdir(parents=True, exist_ok=True)
    data = {
        "model":       pipeline,
        "labels":      LABELS,
        "version":     version,
        "model_type":  model_type,
        "features":    FEATURE_NAMES,
        "trained_at":  time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    joblib.dump(data, output_path)
    logger.info("Model saved to %s", output_path)


# ---------------------------------------------------------------------------
# Personalized model training  (real SAFE rows + synthetic MALICIOUS rows)
# ---------------------------------------------------------------------------

# Minimum real SAFE samples required to train a personalized model.
MIN_REAL_SAMPLES: int = 50

# Ratio: for every 1 real SAFE sample, generate this many synthetic MALICIOUS.
# Keeping malicious ≥ safe prevents the model from being trivially biased.
SYNTHETIC_MALICIOUS_RATIO: int = 3


def load_and_validate_real_csv(csv_path: Path) -> pd.DataFrame:
    """
    Load a behavior-recording CSV and validate its structure.

    The CSV must have at minimum the columns defined in FEATURE_NAMES plus
    a "label" column.  Extra columns (timestamp, pid, exe_path, …) are
    silently dropped.

    Parameters
    ----------
    csv_path : Path
        Path to the behavior-recording CSV exported by the dashboard.

    Returns
    -------
    pd.DataFrame
        Cleaned DataFrame with exactly FEATURE_NAMES + ["label"] columns.

    Raises
    ------
    ValueError
        If required feature columns are missing or the sample count is
        below MIN_REAL_SAMPLES.
    """
    df_raw = pd.read_csv(csv_path)

    # Check which feature columns are present
    missing = [c for c in FEATURE_NAMES if c not in df_raw.columns]
    if missing:
        raise ValueError(
            f"Behavior CSV is missing {len(missing)} feature columns: {missing[:5]}…\n"
            f"Make sure the CSV was exported by the Train-Model tab."
        )

    # Keep only the columns we need; add label if absent (default: safe)
    df = df_raw[FEATURE_NAMES].copy()
    df["label"] = df_raw["label"].str.lower() if "label" in df_raw.columns else "safe"

    # Normalise label: anything that is not malicious/suspicious → safe
    df["label"] = df["label"].apply(
        lambda x: x if x in ("safe", "suspicious", "malicious") else "safe"
    )

    # Enforce numeric features
    for col in FEATURE_NAMES:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0.0)

    n_safe = (df["label"] == "safe").sum()
    if n_safe < MIN_REAL_SAMPLES:
        raise ValueError(
            f"Only {n_safe} safe samples found in {csv_path.name}.  "
            f"Record for longer (need at least {MIN_REAL_SAMPLES} samples)."
        )

    logger.info(
        "Loaded behavior CSV: %d rows (%d safe, %d non-safe) from %s",
        len(df),
        n_safe,
        len(df) - n_safe,
        csv_path,
    )
    return df


def build_personalized_dataset(
    real_df: pd.DataFrame,
    synthetic_ratio: int = SYNTHETIC_MALICIOUS_RATIO,
    seed: int = 42,
) -> Tuple[pd.DataFrame, Dict]:
    """
    Combine real SAFE rows with synthetic MALICIOUS rows.

    Strategy
    --------
    * Count real SAFE samples  → n_safe
    * Generate  n_safe × synthetic_ratio  synthetic MALICIOUS rows
    * Generate  n_safe × 1               synthetic SUSPICIOUS rows
      (adds an intermediate class so the model learns the full spectrum)
    * Concatenate and shuffle

    The final class distribution is roughly:
        safe        ~25 %   (real recordings — user's actual programs)
        suspicious  ~25 %   (synthetic)
        malicious   ~50 %   (synthetic)

    Returns
    -------
    (combined_df, metadata_dict)
    """
    n_real_safe = int((real_df["label"] == "safe").sum())
    n_synthetic_malicious = n_real_safe * synthetic_ratio
    # Add equal suspicious rows to give the model a full three-class view
    n_synthetic_suspicious = n_real_safe

    logger.info(
        "Building personalized dataset: %d real-safe + %d synthetic-malicious "
        "+ %d synthetic-suspicious",
        n_real_safe, n_synthetic_malicious, n_synthetic_suspicious,
    )

    synthetic_df = generate_dataset(
        n_safe=0,                         # no extra safe; we have real ones
        n_suspicious=n_synthetic_suspicious,
        n_malicious=n_synthetic_malicious,
        seed=seed,
    )
    # generate_dataset() includes a "label" column; drop the zero-count safe rows
    synthetic_df = synthetic_df[synthetic_df["label"] != "safe"].reset_index(drop=True)

    combined = pd.concat([real_df, synthetic_df], ignore_index=True)
    combined  = combined.sample(frac=1, random_state=seed).reset_index(drop=True)

    metadata = {
        "real_safe_samples":         n_real_safe,
        "synthetic_malicious_samples": n_synthetic_malicious,
        "synthetic_suspicious_samples": n_synthetic_suspicious,
        "total_samples":              len(combined),
    }
    return combined, metadata


def save_model_with_metadata(
    pipeline,
    output_path: Path,
    model_type: str,
    version: str,
    extra_metadata: Optional[Dict] = None,
) -> None:
    """
    Save a trained pipeline together with optional training metadata.

    In addition to the standard joblib payload this also writes a
    human-readable JSON sidecar at  <output_path>.json  so users can
    inspect training stats without loading the model.

    Parameters
    ----------
    pipeline       : fitted sklearn Pipeline.
    output_path    : destination .joblib path.
    model_type     : "gb" or "rf".
    version        : version string.
    extra_metadata : dict merged into both joblib payload and JSON sidecar.
    """
    import joblib

    output_path.parent.mkdir(parents=True, exist_ok=True)

    now_iso = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    data = {
        "model":       pipeline,
        "labels":      LABELS,
        "version":     version,
        "model_type":  model_type,
        "features":    FEATURE_NAMES,
        "trained_at":  now_iso,
    }
    if extra_metadata:
        data.update(extra_metadata)

    joblib.dump(data, output_path)
    logger.info("Model saved to %s", output_path)

    # Write human-readable JSON sidecar (excludes the sklearn object itself)
    sidecar_path = output_path.with_suffix(".json")
    sidecar = {k: v for k, v in data.items() if k != "model"}
    sidecar["trained_at"] = now_iso
    sidecar_path.write_text(
        json.dumps(sidecar, indent=2, default=str), encoding="utf-8"
    )
    logger.info("Metadata sidecar written to %s", sidecar_path)


def train_personalized(
    csv_path: Path,
    output_path: Optional[Path] = None,
    model_type: str = "gb",
    n_estimators: int = 300,
    cv_folds: int = 5,
    seed: int = 42,
    version: str = "personalized-1.0",
    progress_callback: Optional[Callable[[str, float], None]] = None,
) -> Dict:
    """
    Full personalized-model training pipeline called by the dashboard.

    Steps
    -----
    1. Load and validate the behavior-recording CSV.
    2. Build a balanced dataset (real SAFE + synthetic MALICIOUS/SUSPICIOUS).
    3. Train a Gradient Boosting pipeline with cross-validation.
    4. Save the model as  models/keylogger_detector_personalized.joblib
       plus a JSON metadata sidecar.

    Parameters
    ----------
    csv_path          : Path to the behavior-recording CSV.
    output_path       : Override output path (default: personalized model path).
    model_type        : "gb" or "rf".
    n_estimators      : Number of trees.
    cv_folds          : Cross-validation folds.
    seed              : Random seed.
    version           : Version string embedded in the model.
    progress_callback : Optional callable(message: str, fraction: float).
                        Fraction is 0.0–1.0.  Used by the dashboard progress bar.

    Returns
    -------
    dict with keys:
        success        (bool)
        accuracy       (float, 0–1)
        cv_f1_mean     (float)
        cv_f1_std      (float)
        n_real_safe    (int)
        n_synthetic    (int)
        n_total        (int)
        model_path     (str)
        error          (str or None)
    """
    def _progress(msg: str, pct: float) -> None:
        logger.info("[%.0f%%] %s", pct * 100, msg)
        if progress_callback:
            try:
                progress_callback(msg, pct)
            except Exception:
                pass

    out_path = Path(output_path) if output_path else (
        PROJECT_ROOT / "models" / "keylogger_detector_personalized.joblib"
    )

    try:
        # Step 1 — Load CSV
        _progress("Loading behavior recording CSV…", 0.05)
        real_df = load_and_validate_real_csv(csv_path)

        # Step 2 — Build balanced dataset
        _progress("Building balanced training dataset…", 0.15)
        combined_df, meta = build_personalized_dataset(real_df, seed=seed)

        # Step 3 — Train
        _progress("Running cross-validation…", 0.30)
        pipeline, report, cv_scores = train(
            combined_df,
            model_type=model_type,
            n_estimators=n_estimators,
            cv_folds=cv_folds,
            seed=seed,
        )
        _progress("Training complete. Evaluating…", 0.80)

        # Derive a simple accuracy from the classification report
        from sklearn.metrics import accuracy_score
        from sklearn.model_selection import train_test_split
        X = combined_df[FEATURE_NAMES].values.astype("float32")
        y = combined_df["label"].values
        _, X_test, _, y_test = train_test_split(
            X, y, test_size=0.20, stratify=y, random_state=seed
        )
        y_pred = pipeline.predict(X_test)
        accuracy = float(accuracy_score(y_test, y_pred))

        # Step 4 — Save
        _progress("Saving personalized model…", 0.90)
        extra = {
            "model_type_label":             "personalized",
            "real_safe_samples":            meta["real_safe_samples"],
            "synthetic_malicious_samples":  meta["synthetic_malicious_samples"],
            "synthetic_suspicious_samples": meta["synthetic_suspicious_samples"],
            "total_samples":                meta["total_samples"],
            "accuracy":                     round(accuracy, 4),
            "cv_f1_mean":                   round(float(cv_scores.mean()), 4),
            "cv_f1_std":                    round(float(cv_scores.std()),  4),
            "source_csv":                   str(csv_path),
        }
        save_model_with_metadata(pipeline, out_path, model_type, version, extra)

        _progress("Done!", 1.0)

        return {
            "success":    True,
            "accuracy":   accuracy,
            "cv_f1_mean": float(cv_scores.mean()),
            "cv_f1_std":  float(cv_scores.std()),
            "n_real_safe":   meta["real_safe_samples"],
            "n_synthetic":   meta["synthetic_malicious_samples"] + meta["synthetic_suspicious_samples"],
            "n_total":       meta["total_samples"],
            "model_path":    str(out_path),
            "error":         None,
        }

    except Exception as exc:
        logger.error("train_personalized failed: %s", exc, exc_info=True)
        return {
            "success":   False,
            "accuracy":  0.0,
            "cv_f1_mean": 0.0,
            "cv_f1_std":  0.0,
            "n_real_safe": 0,
            "n_synthetic": 0,
            "n_total":     0,
            "model_path":  "",
            "error":       str(exc),
        }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="train_model",
        description="Generate synthetic training data and train the keylogger detector model.",
    )
    p.add_argument("--samples", type=int, default=3000,
                   help="Total synthetic samples to generate (split 50/25/25 safe/suspicious/malicious). Default: 3000")
    p.add_argument("--model-type", choices=["gb", "rf"], default="gb",
                   help="gb=GradientBoosting (default), rf=RandomForest")
    p.add_argument("--estimators", type=int, default=300,
                   help="Number of trees/estimators. Default: 300")
    p.add_argument("--cv-folds", type=int, default=5,
                   help="Stratified k-fold CV folds. Default: 5")
    p.add_argument("--output", type=Path,
                   default=PROJECT_ROOT / "models" / "keylogger_detector.joblib",
                   help="Output path for serialised model.")
    p.add_argument("--csv", type=Path, default=None,
                   help="Save generated dataset to this CSV path.")
    p.add_argument("--load-csv", type=Path, default=None,
                   help="Train on this existing labelled CSV instead of generating data.")
    # NEW: load a behavior-recording CSV of real SAFE samples and mix with
    # synthetic MALICIOUS samples for personalized model training.
    p.add_argument("--load-real-csv", type=Path, default=None,
                   help=(
                       "Path to a behavior-recording CSV (all rows labelled 'safe'). "
                       "The script will generate 3× synthetic malicious rows to "
                       "balance the dataset and save the model as "
                       "keylogger_detector_personalized.joblib."
                   ))
    p.add_argument("--seed", type=int, default=42,
                   help="Random seed for reproducibility.")
    p.add_argument("--version", type=str, default="1.0",
                   help="Version string embedded in the saved model.")
    return p


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )

    args = _build_parser().parse_args()

    # ------------------------------------------------------------------
    # Load or generate dataset
    # ------------------------------------------------------------------
    if args.load_real_csv:
        # Personalized training: real SAFE recordings + synthetic MALICIOUS
        logger.info(
            "Personalized training mode — loading real CSV: %s",
            args.load_real_csv,
        )
        result = train_personalized(
            csv_path=args.load_real_csv,
            output_path=PROJECT_ROOT / "models" / "keylogger_detector_personalized.joblib",
            model_type=args.model_type,
            n_estimators=args.estimators,
            cv_folds=args.cv_folds,
            seed=args.seed,
            version=f"personalized-{args.version}",
        )
        if result["success"]:
            print("\n✅ Personalized model trained successfully!")
            print(f"   Accuracy        : {result['accuracy']:.1%}")
            print(f"   CV F1-macro     : {result['cv_f1_mean']:.3f} ± {result['cv_f1_std']:.3f}")
            print(f"   Real SAFE rows  : {result['n_real_safe']}")
            print(f"   Synthetic rows  : {result['n_synthetic']}")
            print(f"   Total samples   : {result['n_total']}")
            print(f"   Saved to        : {result['model_path']}")
        else:
            print(f"\n❌ Personalized training failed: {result['error']}")
            return 1
        return 0

    elif args.load_csv:
        logger.info("Loading dataset from %s…", args.load_csv)
        df = pd.read_csv(args.load_csv)
        # Validate required columns
        missing = [c for c in FEATURE_NAMES + ["label"] if c not in df.columns]
        if missing:
            logger.error("CSV is missing required columns: %s", missing)
            return 1
        logger.info("Loaded %d rows from CSV.", len(df))
    else:
        n_total      = args.samples
        n_safe       = n_total // 2
        n_suspicious = n_total // 4
        n_malicious  = n_total - n_safe - n_suspicious
        df = generate_dataset(
            n_safe=n_safe,
            n_suspicious=n_suspicious,
            n_malicious=n_malicious,
            seed=args.seed,
        )
        if args.csv:
            args.csv.parent.mkdir(parents=True, exist_ok=True)
            df.to_csv(args.csv, index=False)
            logger.info("Dataset saved to %s", args.csv)

    # ------------------------------------------------------------------
    # Class distribution summary
    # ------------------------------------------------------------------
    print("\n--- Dataset Summary ---")
    counts = df["label"].value_counts()
    for cls in LABELS:
        n = counts.get(cls, 0)
        pct = 100 * n / len(df)
        print(f"  {cls:<12} {n:>5}  ({pct:.1f}%)")
    print(f"  {'TOTAL':<12} {len(df):>5}")

    # ------------------------------------------------------------------
    # Train
    # ------------------------------------------------------------------
    print(f"\n--- Training ({args.model_type.upper()}, {args.estimators} estimators) ---")
    pipeline, report, cv_scores = train(
        df,
        model_type=args.model_type,
        n_estimators=args.estimators,
        cv_folds=args.cv_folds,
        seed=args.seed,
    )

    # ------------------------------------------------------------------
    # Results
    # ------------------------------------------------------------------
    print("\n--- Cross-Validation (F1-macro) ---")
    print(f"  Folds  : {cv_scores}")
    print(f"  Mean   : {cv_scores.mean():.3f}")
    print(f"  Std    : {cv_scores.std():.3f}")

    print("\n--- Test Set Classification Report ---")
    print(report)

    _print_feature_importance(pipeline)

    # ------------------------------------------------------------------
    # Save
    # ------------------------------------------------------------------
    save_model_with_metadata(pipeline, args.output, args.model_type, args.version)
    print(f"\nModel written to: {args.output}")
    print("The running detector will hot-reload this file within 60 seconds.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
